SELECT 
(CASE WHEN sum(NUMBER1) %2 = 1 THEN MIN(NUMBER1) 
          ELSE MAX(NUMBER1)
               END) AS NUMBER1,
(CASE WHEN sum(NUMBER2) %2 = 1 THEN MIN(NUMBER2) 
          ELSE MAX(NUMBER2)
               END) AS NUMBER2
FROM NUMBERS